### ISSUE TITLE
Pixel 7a issue closing apps after android 16 update.

### ISSUE THREAD

**Issue by dealerdahl** [GrapheneOS/os_issue_tracker#5803]
device: pixel 7a
version: 2025070800 stable

when using gestures to close apps, sometimes the app gets stuck while selected.
i can drag the app to the side and tap "Clear all" but not swipe up to close it.
it happens when i open my phone after entering my pin, but not if i only just opened the app while already using my phone.

**Comment by Hesky05** [comment]
Same issue. Swiping up just sends the app card sideways unless I swipe up from above halfway up the screen.

**Comment by smexyy** [comment]
Same issue in pixel 6a ( 2025071900 ) stable

**Comment by dealerdahl** [comment]
the issue seems to have been resolved. anybody else?

**Comment by ToughDBlue** [comment]
This is still happening on my Pixel 7, my wife's Pixel 7, and my daughter's Pixel 9.

**Comment by thestinger** [comment]
@ToughDBlue File a new issue with a clear description.
